marketplace_l6/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Models\Category;
use App\Models\Product;
use App\Models\Store;
use App\Http\Controllers\Admin\StoreController;
use App\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});
//EXAMPLE WORKING WITH ELOQUENT
Route::get('/model', function () {

    // $data = DB::table('users')->whereBetween('id', ['10', '67'])->get();// retorna todos os campos que então no intervalo entre 10 e 67 ;
    // $data = DB::table('users')->orderBy('name', 'ASC')->paginate(10);//http://127.0.0.1:8000/model?page=36   paginas dados com laravel

    //Mass Assigment -> Atribuição em Massa create([]) salva automaticamente , precisa que o model tenha o metodo fillable


    /*   $data[''] = User::create([
           'name' => 'pedro augusto',
           'email' => 'pedroaugusto@example.br',
           'password' => bcrypt('12345')
       ]);
       if (!$data) {
           $data['status'] = '200';
           $data['msg'] = 'user created with success!!.';

       } else {
           $data['status'] = '404';
           $data['msg'] = 'cannot created user..';
       }*/

    //Mass update -> return true or false

    /*$data['data'] = User::find(40)->update([
        'name' => 'carol',
        'email' => 'carol@example.br',
        'password' => bcrypt('1234534')];
     if ($data) {
        $data['status'] = '200';
        $data['msg'] = 'user updated with success!!.';
        return response()->json($data->store);
    } else {
        $data['status'] = '404';
        $data['msg'] = 'cannot update user..';
    }

    return response()->json($data);
    ]);*/

    // pegar a loja de um usuario
    //$data = User::find(34);
    // return $data->store;  // 1:1 ->retorna objecto unicp
    //return $data->store()->count();  // quantas loja o usuario tem

    //Pegar os produtos de uma loja ?
    //$stores = Store::find(9);
    //return $stores->products()->where('id',9)->get();

    //pegar as categorais de uma loja

    //$categories = Category::find(3);
    //return $categories->products;

    /**
     * 1- criar uma loja para um usuário
     * 2- criar um produto para uma loja
     * 3-criar uma  categoria
     */

    /*1- criar uma loja para um usuário
    $user = User::find(10);

    $store = $user->store()->create([
        'name' => 'Loja Teste',
        'slug' => 'loja-teste',
        'phone' => '000 000 000',
        'description' => 'loja-teste de produtos',
    ]);
    dd($store);*/

    //2- criar um produto para uma loja
    $user = Store::find(40);

    $products = $user->products()->create([
        'nome' => 'Notebook Dell',
        'slug' => 'loja-produtos',
        'description' => 'CORE I6 123TB',
        'body' => 'anything here is enough...',
        'price' => 1023, 99,
    ]);
    //return response()->json($products);

    // -> criar uma categoria

    /* $categoria = Category::create([
        'name' => 'Devices',
        'slug' => 'Devices mad  by Wayne Corporation',
        'description' => 'Computers',
    ]);

     $categoria1 = Category::create([
        'name' => 'Games',
        'slug' => 'games',
        'description' => 'football manager 2022',
    ]);
    return response()->json([$categoria,$categoria1]);

*/// -> adicionar produtos para uma categoria ou vice-versa .attach pega o id e adiciona na base de dados
    //attach()->retorna null quando o valor é adicionado
    //detach()->apaga o valor adicionado e retorna a quqntidade de items removido 1
    //sync([])->retorna full information-> remove e addiciona elementos . id de linhas que existem na base de dados
    $products = Product::find(44);
    //$dados = $products->categories()->attach([1]);
    //$dados = $products->categories()->detach([1]);
    $dados = $products->categories()->sync([1, 2]); //add
    $dados = $products->categories()->sync([1]); //remove
    dd($dados);
});

Route::prefix('admin')->namespace('Admin')->group(function () {
    Route::get('/index', 'StoreController@index')->name('admin.index');
    Route::get('/create', 'StoreController@create')->name('admin.create');
    Route::post('/store', 'StoreController@store')->name('admin.store');
    Route::get('/{store}/edit', 'StoreController@edit')->name('admin.edit');
    Route::put('/update/{store}', 'StoreController@update')->name('admin.update');
    Route::delete('/destroy/{store}', 'StoreController@destroy')->name('admin.destroy');

    //Products route
    Route::resource('product', 'ProductController');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

marketplace_l6/app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    //
    protected $table = 'products';
    protected $fillable = ['nome', 'slug', 'description', 'body', 'price'];

    /**
     * product belongsTo store
     */
    function store()
    {

        return $this->belongsTo(Store::class);
    }

    /**
     * product belongs to many categories'
     * produto pertence a muitas categorias ->pt
     */
    function categories()
    {
        return $this->belongsToMany(Category::class);
    }


}

marketplace_l6/app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Product;
use App\Models\Store;
use App\User;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    private $product;

    function __construct(Product $product)
    {
        $this->product = $product;
    }

    /**
     * Display a listing of the resource.
     *
     * @return
     */
    public function index()
    {
        $products = $this->product->paginate(10);
        return view('admin.products.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return
     */
    public function create()
    {
        $stores = Store::all(['id', 'name']);
        return view('admin.products.create', compact('stores'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return
     */
    public function store(Request $request)
    {
        $request->validate(

            [
                'nome' => 'required|string|min:5',
                'slug' => 'required|string|min:10',
                'description' => 'required|string|min:10',
                'body' => 'required|string|min:10',
                'price' => 'required|',
            ]);
        $store = Store::findOrFail(20);
        $product = $store->products()->create([
            'nome' => $request->input('nome'),
            'slug' => $request->input('slug'),
            'description' => $request->input('description'),
            'body' => $request->input('body'),
            'price' => $request->input('price'),

        ]);
        return redirect()->route('product.index')->with('message', 'new store created with success!!');
    }

    /**
     * Display the specified resource.
     *
     * @param int $product
     *
     */
    public function show($product)
    {
        return $product;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $product
     * @return
     */
    public function edit($product)
    {
        $product = $this->product->findOrFail($product);
        return view('admin.products.edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $product
     * @return
     */
    public function update(Request $request, $product)
    {
        $request->validate(

            [
                'nome' => 'required|string|min:5',
                'slug' => 'required|string|min:10',
                'description' => 'required|string|min:10',
                'body' => 'required|string|min:10',
                'price' => 'required|',
            ]);
        $product = $this->product->findOrFail($product);
        $product->update([
            'nome' => $request->input('nome'),
            'slug' => $request->input('slug'),
            'description' => $request->input('description'),
            'body' => $request->input('body'),
            'price' => $request->input('price'),

        ]);
        return redirect()->route('product.index')->with('message', 'product updated with success!!!!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $product
     *
     */
    public function destroy($product)
    {
        $product = $this->product->findOrFail($product);
        $product->delete();
        return redirect()->route('product.index')->with('message', 'product deleted with success!!!!');
    }
}

marketplace_l6/resources/views/admin/products/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Create New Store</div>
                    <div class="card-body">
                        <form action="{{route('product.store')}}" method="post">
                            @csrf
                            <div class="form-group">
                                <label for="nome">Name Product</label>
                                <input type="text" class="form-control {{$errors->has('nome') ? 'border-danger': ''}}"
                                       id="nome" name="nome" value="{{old('nome')}}">
                                <small class="form-text text-danger">{{$errors->first('nome')}}</small>
                            </div>
                            <div class="form-group">
                                <label for="store">Store</label>
                                <select class="form-control {{$errors->has('store') ? 'border-danger': ''}}"
                                        id="store" name="store" value="{{old('store')}}">
                                    @foreach($stores as $store)
                                        <option value="{{$store->id}}">{{$store->name}}</option>
                                    @endforeach
                                </select>
                                <small class="form-text text-danger">{{$errors->first('user')}}</small>
                            </div>
                            <div class="form-group">
                                <label for="slug">Slug</label>
                                <input type="text" class="form-control {{$errors->has('slug') ? 'border-danger': ''}}"
                                       id="slug" name="slug" value="{{old('slug')}}">
                                <small class="form-text text-danger">{{$errors->first('slug')}}</small>
                            </div>
                            <div class="form-group">
                                <label for="description">Description</label>
                                <textarea class="form-control {{$errors->has('description') ? 'border-danger': ''}} "
                                          id="description" value="{{old('description')}}"
                                          name="description" rows="5"></textarea>
                                <small class="form-text text-danger">{{$errors->first('description')}}</small>
                            </div>
                            <div class="form-group">
                                <label for="body">Body</label>
                                <textarea type="body"
                                          class="form-control {{$errors->has('body') ? 'border-danger': ''}}"
                                          id="body" name="body" value="{{old('body')}}"></textarea>
                                <small class="form-text text-danger">{{$errors->first('body')}}</small>
                            </div>
                            <div class="form-group">
                                <label for="price">Price</label>
                                <input type="number" step="0.01"
                                       class="form-control {{$errors->has('price') ? 'border-danger': ''}}"
                                       id="price" name="price" value="{{old('price')}}">
                                <small class="form-text text-danger">{{$errors->first('price')}}</small>
                            </div>
                            <input style="margin-top: 100px;" class="btn btn-primary " type="submit" value="Save Store">
                        </form>
                        <a style="margin-bottom: 900px;" class="btn btn-primary  float-right"
                           href="{{route('product.index')}}"><i
                                class="fas fa-arrow-circle-up"></i> Back</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

marketplace_l6/resources/views/admin/products/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Edit Product</div>
                    <div class="card-body">
                        <form action="{{route('product.index')}}/{{$product->id}}" method="post">
                            @method('PUT')
                            @csrf
                            <div class="form-group">
                                <label for="nome">Name</label>
                                <input type="text" class="form-control {{$errors->has('nome') ? 'border-danger': ''}}"
                                       id="nome" name="nome" value="{{$product->name ?? old('nome')}}">
                                <small class="form-text text-danger">{{$errors->first('name')}}</small>
                            </div>

                            <div class="form-group">
                                <label for="slug">Slug</label>
                                <input type="text" class="form-control {{$errors->has('slug') ? 'border-danger': ''}}"
                                       id="slug" name="slug" value="{{$product->slug ?? old('slug')}}">
                                <small class="form-text text-danger">{{$errors->first('slug')}}</small>
                            </div>

                            <div class="form-group">
                                <label for="description">Description</label>
                                <textarea class="form-control {{$errors->has('description') ? 'border-danger': ''}} "
                                          id="description" value="{{$product->description ?? old('description')}}"
                                          name="description" rows="5"></textarea>
                                <small class="form-text text-danger">{{$errors->first('description')}}</small>
                            </div>
                            <div class="form-group">
                                <label for="body">Body</label>
                                <textarea type="text"
                                          class="form-control {{$errors->has('body') ? 'border-danger': ''}}"
                                          id="body" name="body" value="{{$product->body ?? old('body')}}"></textarea>
                                <small class="form-text text-danger">{{$errors->first('body')}}</small>
                            </div>
                            <div class="form-group">
                                <label for="price">Price</label>
                                <input type="number" step="0.01" class="form-control {{$errors->has('price') ? 'border-danger': ''}}"
                                       id="price" name="price" value="{{$product->price ?? old('price')}}">
                                <small class="form-text text-danger">{{$errors->first('price')}}</small>
                            </div>

                            <input class="btn btn-primary mt-4" type="submit" value="Update Product">
                        </form>
                        <a class="btn btn-primary float-right" href="{{route('product.index')}}"><i
                                class="fas fa-arrow-circle-up"></i> Back</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

marketplace_l6/resources/views/admin/products/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-12 col-md-12 col-sm-12 col-xl-12">
                <div class="card p-2">
                    <h3 align="center">Products</h3>
                    <div class="table-responsive">
                        <table id="product" class="table table-striped display" style="width:100%">
                            <thead>
                            <tr>
                                <th scope="col">ID</th>
                                <th scope="col">Store_id</th>
                                <th scope="col">Name</th>
                                <th scope="col">Slug</th>
                                <th scope="col">Description</th>
                                <th scope="col">Body</th>
                                <th scope="col">Price</th>

                            </tr>
                            </thead>
                            @foreach($products as $product)
                                <tr>
                                    <tbody>

                                    <td>{{$product->id}}</td>
                                    <td>{{$product->store_id}}</td>
                                    <td>{{$product->nome}}</td>
                                    <td>{{$product->slug}}</td>
                                    <td>{{$product->description}}</td>
                                    <td>{{$product->body}}</td>
                                    <td>&euro; {{$product->price}}</td>
                                    <td>

                                        <a class="btn btn-sm btn-outline-success
" href="{{route('product.edit',['product'=>$product->id])}}">
                                            Edit Store
                                        </a>
                                    </td>
                                    <td>
                                        <form
                                            action="{{route('product.destroy',['product'=>$product->id])}}"
                                            method="post">
                                            @method('DELETE')
                                            @csrf
                                            <input class="btn btn-sm  btn-outline-danger" type="submit" value="delete">
                                        </form>

                                    </td>


                                    </tbody>


                                </tr>
                            @endforeach
                        </table>
                        {{$products->links()}}

                        <div class="mt-4">
                            <a href="{{route('product.create')}}" class=" btn btn-success btn-lg"> <i
                                    class="fas fa-plus-circle"></i> Create Products </a>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection